### ISSUE TITLE
in the readme add what details should be provided in a request and have a sample request format

### ISSUE THREAD

**Issue by RustoMCSpit** [instatetragrammaton/Patches#3]

**Comment by instatetragrammaton** [comment]
Here you go! https://github.com/instatetragrammaton/Patches/blob/master/Synthesis/Requests.md (linked from the main README.md).

**Comment by RustoMCSpit** [comment]
alright i read it but my request is vague by nature. can you make a set of Surge XT patches but have them all designed for audio input. I want to run my guitar and vocals through it. To do that, the audio needs to be sidechained into Surge and Surge needs its oscillator(s) set to Audio input and it needs to be in latch mode. i dont care about the emotion and i have no reference so genuinely just come up with whatever lmfao!

**Comment by RustoMCSpit** [comment]
![image](https://github.com/instatetragrammaton/Patches/assets/134429563/a5b3dfa3-7acf-4982-b07f-4cb577740709)
![image](https://github.com/instatetragrammaton/Patches/assets/134429563/c20b29c4-c86a-4a18-9633-9cc6f45b9aa4)

you could include these in the readme as advice for people who want to make their own
